name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'Acceptance'
        type: choice
        options:
          - 'Acceptance'
          - 'Production'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm run deploy:prepare
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .deploy/deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.event.inputs.environment }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: node-app
      - run: unzip deploy.zip
      - id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ vars.APP_NAME }}'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
